### ISSUE TITLE
3ds crash on exit

### ISSUE THREAD

**Issue by ShineMan7** [matbo87/snes9x_3ds#20] opened 2024-03-06 20:14 UTC
The entire system crashes when I quit the emulator, whether it is through the home screen or the app itself. I am on version 1.51.1 (at least based on the universal updater). This is the error message I get whenever I close it:
![IMG_20240306_220628](https://github.com/matbo87/snes9x_3ds/assets/153309990/d20cbf5b-71f7-43d8-9db4-26176d21ac44)

**Comment by matbo87** [comment] 2024-03-09 12:38
I wasn't able to reproduce the crash. Successfully tested on N3DS, using the cia version from universal updater. Were you running a specific game before exiting the emulator?
Looks like the crash on your device is happening when the emulator updates settings.cfg on exit. You could delete the 3ds/snes9x_3ds folder and try again. Sometimes files get corrupted.
If the problem persists, try Snes9x from bubble2k, which is also available via universal updater.  If this version also crashes on your device, at least it's not a version-specific issue ;)

**Comment by Anonymous941** [comment] 2024-03-09 16:37
You can also try disabling external FIRMs and modules, and game patching in Luma3DS settings temporarily (hold select on boot, and uncheck  those two) and see if it still happens

**Comment by ShineMan7** [comment] 2024-03-09 18:39
Disabling those 2 options didn't seem to do anything. I'll try deleting the snes9x folder and if it doesn't work, I'll install the original fork.

**Comment by matbo87** [comment] 2024-04-14 09:48
Closed as it appears to be a user-specific problem and the user has not provided any further useful information (e.g. reproduction steps)

**Closed by matbo87** 2024-04-14 09:48 UTC
